CREATE TABLE entity (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"name" varchar NOT NULL,
	CONSTRAINT entity_pkey PRIMARY KEY (id)
);

INSERT INTO public.entity (id,"name") VALUES(1,'POSTGRES');
